const API = localStorage.getItem('autoresearch_api') || 'http://127.0.0.1:8090';
window.addEventListener('error',e=>console.warn('AutoResearch UI error',e.error||e.message));
const stages = [['SEARCHING','LIT'],['EVIDENCE_READY','EVD'],['HYPOTHESES_READY','HYP'],['IMPLEMENTING','COD'],['RUNNING','RUN'],['AWAITING_DEPENDENCY_APPROVAL','DEP'],['ANALYZING','ANA'],['REVIEWING','REV'],['REPORT_READY','DOC']];
let missions = [], selected = null, timer = null, literatureMode = 'live';
const CONFIG_KEY = 'autoresearch_runtime_config';
function splitCommand(value){const matches=value.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)||[];return matches.map(x=>x.replace(/^(["']).*\1$/,'').replace(/^['"]|['"]$/g,''));}
const $ = (id) => document.getElementById(id);
// Version the preference so the first release with the switch always opens
// in the original dark console instead of inheriting an accidental prototype
// value from an earlier UI build.
const THEME_KEY = 'autoresearch_theme_v2';
const savedTheme = localStorage.getItem(THEME_KEY) || 'dark';
function applyTheme(theme){ document.body.classList.toggle('light', theme === 'light'); const toggle=$('themeToggle'); if(toggle){toggle.setAttribute('aria-checked', String(theme === 'light'));toggle.setAttribute('aria-label', theme === 'light' ? '切换深色主题' : '切换浅色主题');} }
applyTheme(savedTheme);
// Live metadata is the safe default; Fixture is explicitly opt-in demo data.
document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('active',c.dataset.mode==='live'));
const configNote=document.querySelector('.config-note');if(configNote)configNote.innerHTML='真实 CLI 的 API Key 不在这里填写，只从本机环境变量读取。Coding Agent 完成后，Compute 会自动发现并运行实验入口；METRIC 为 auto 时由结果自动选择。';
function ensureRuntimeFields(){const grid=document.querySelector('.config-grid');if(!grid)return;['computeCommand','computeCwd','codingCommand'].forEach(id=>$(id)?.closest('label')?.remove());document.querySelector('#codingAgent option[value="command"]')?.remove();if(!$('deerflowCwd')){const wrap=document.createElement('label');wrap.innerHTML='DEERFLOW WORKSPACE<input id="deerflowCwd" placeholder="F:\\AutoDeepResearch\\third_party\\deer-flow-main" />';grid.insertBefore(wrap,grid.firstElementChild)}}
function ensureObjectiveMetric(){if($('objectiveMetric'))return;const controls=document.querySelector('.mission-controls');if(!controls)return;const label=document.createElement('label');label.innerHTML='METRIC <input id="objectiveMetric" class="metric-input" value="auto" placeholder="auto" title="留空由实验结果自动选择" />';controls.insertBefore(label,controls.firstElementChild)}
function loadRuntimeConfig(){try{const c=JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}');for(const [id,value] of Object.entries(c)){const el=$(id);if(el&&value!=null)el.value=value}}catch(_){}}
function runtimeConfig(){const ids=['codingAgent','codingCwd','codingCommand','computeCommand','computeCwd','deerflowCwd','codexExecutable','claudeExecutable','objectiveMetric'];const out={};ids.forEach(id=>{const el=$(id);if(el&&el.value.trim())out[id]=el.value.trim()});localStorage.setItem(CONFIG_KEY,JSON.stringify(out));return out}
const stageActivity={SEARCHING:'正在检索文献与资料',EVIDENCE_READY:'正在整理证据链',HYPOTHESES_READY:'正在生成可检验假设',IMPLEMENTING:'Coding Agent 正在实现实验',RUNNING:'实验执行器正在运行实验',AWAITING_DEPENDENCY_APPROVAL:'等待用户批准安装实验依赖',ANALYZING:'正在分析实验结果',REVIEWING:'Reviewer 正在审查结果',REPORT_READY:'研究报告已生成',FAILED:'任务执行失败',CANCELLED:'任务已取消',DRAFT:'等待启动'};
function ensureActivityBanner(){if($('activityBanner')||!$('detailMeta'))return;const el=document.createElement('div');el.id='activityBanner';el.className='activity-banner';el.innerHTML='<span class="activity-spinner"></span><div><small>LIVE ACTIVITY</small><strong id="activityText">等待任务状态…</strong></div><span class="activity-pulse">●</span>';$('detailMeta').after(el)}
function ensureTrace(){if($('tracePanel')||!$('activityBanner'))return;const el=document.createElement('details');el.id='tracePanel';el.className='trace-panel';el.innerHTML='<summary><span>TRACE</span><b id="traceSummary">状态转换记录</b><i>⌄</i></summary><div id="traceList" class="trace-list"></div>';$('activityBanner').after(el)}
function ensurePauseControls(){const box=document.querySelector('.detail-actions');if(!box||$('pauseBtn'))return;const b=document.createElement('button');b.id='pauseBtn';b.className='pause-btn';b.textContent='PAUSE';box.insertBefore(b,box.firstElementChild);const d=document.createElement('button');d.id='deleteBtn';d.className='pause-btn';d.textContent='DELETE';box.insertBefore(d,box.firstElementChild)}
function syncPauseButton(task){const b=$('pauseBtn');if(!b||!task)return;const dependencyGate=task.state==='AWAITING_DEPENDENCY_APPROVAL';const paused=task.state==='PAUSED';const terminal=['REPORT_READY','FAILED','CANCELLED'].includes(task.state);b.textContent=dependencyGate?'REVIEW DEPENDENCIES':paused?'RESUME':'PAUSE';b.disabled=terminal||(!dependencyGate&&!paused&&!['queued','running'].includes(task.execution_status));b.title=dependencyGate?'审核并决定是否安装实验依赖':paused?'恢复研究任务':'暂停研究任务';b.classList.toggle('resume-btn',paused||dependencyGate)}
const toast = (msg) => { const el=$('toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600); };
async function api(path, options={}) { const res=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); const data=await res.json(); if(!res.ok) throw new Error(data.message||data.error||`HTTP ${res.status}`); return data; }
function stateClass(state){return state==='FAILED'||state==='CANCELLED'?'failed':''}
function renderMissions(){ $('missionCount').textContent=String(missions.length).padStart(2,'0'); const box=$('missions'); if(!missions.length){box.innerHTML='<div class="empty-state">No missions yet. Your next discovery starts above.</div>';return} box.innerHTML=missions.map((m,i)=>{const active=!['REPORT_READY','FAILED','CANCELLED'].includes(m.state);const created=m.created_at?new Date(m.created_at).toLocaleString():'—';return `<div class="mission-row" data-id="${m.task_id}"><span class="mission-index">${active?'<span class="mini-spinner"></span>':String(i+1).padStart(2,'0')}</span><span class="mission-title">${escapeHtml(m.question||'Untitled mission')}<small class="mission-created">${escapeHtml(created)}</small></span><span class="mission-date">${(m.execution_status||'idle').toUpperCase()}</span><span class="state-pill ${stateClass(m.state)}">${m.state}</span></div>`}).join(''); box.querySelectorAll('.mission-row').forEach(row=>row.onclick=()=>openMission(row.dataset.id)); }
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function loadMissions(){try{const data=await api('/research');missions=data.tasks||[];renderMissions();if(selected) await refreshDetail(selected)}catch(e){toast(`API unavailable · ${e.message}`)}}
async function launch(){const question=$('question').value.trim();if(!question){toast('先输入一个科研问题');$('question').focus();return}const cfg=runtimeConfig();if(cfg.codingAgent==='command'&&!cfg.codingCommand){toast('Custom command mode needs a coding command');return}if(cfg.codingAgent!=='fake'&&!cfg.codingCwd){toast('真实 Coding Agent 需要填写工作目录');return}if(cfg.computeCommand&&!cfg.computeCwd){toast('填写实验工作目录');return}const btn=$('launchBtn');btn.disabled=true;btn.innerHTML='Initializing <span>…</span>';try{const payload={question,async:true,auto_approve:true,literature:literatureMode,iterations:Number($('iterations').value)||2,replicates:Number($('replicates').value)||2,objective_metric:cfg.objectiveMetric||'score',objective_direction:'max',coding_agent:cfg.codingAgent||'fake'};if(cfg.codingCwd)payload.coding_cwd=cfg.codingCwd;if(cfg.codingCommand)payload.coding_command=splitCommand(cfg.codingCommand);if(cfg.computeCommand)payload.compute_command=splitCommand(cfg.computeCommand);if(cfg.computeCwd)payload.compute_cwd=cfg.computeCwd;if(cfg.deerflowCwd)payload.deerflow_cwd=cfg.deerflowCwd;if(cfg.codexExecutable)payload.codex_executable=cfg.codexExecutable;if(cfg.claudeExecutable)payload.claude_executable=cfg.claudeExecutable;const data=await api('/research',{method:'POST',body:JSON.stringify(payload)});toast(cfg.codingAgent==='fake'?'Demo mission initialized':'Real mission queued');$('question').value='';await loadMissions();if(data.task) openMission(data.task.task_id)}catch(e){toast(`Launch failed · ${e.message}`)}finally{btn.disabled=false;btn.innerHTML='Launch mission <span>↗</span>'}}
async function openMission(id){selected=id;$('overviewView').classList.add('hidden');$('detailView').classList.remove('hidden');$('viewName').textContent='MISSION';ensurePauseControls();if($('insight'))$('insight').innerHTML='<div class="signal-ring">◎</div><p>Loading mission artifacts...</p>';if($('artifacts'))$('artifacts').innerHTML='<div class="empty-state">Loading artifacts...</div>';await refreshDetail(id);if(timer)clearInterval(timer);timer=setInterval(()=>refreshDetail(id),2500)}
async function refreshDetail(id){try{const [taskData,statusData,artsData,jobData]=await Promise.all([api(`/research/${id}`),api(`/research/${id}/status`),api(`/research/${id}/artifacts`),api(`/research/${id}/job`).catch(()=>({}))]);const task=taskData.task;const status=statusData.status||{};const artifacts=artsData.artifacts||[];ensureActivityBanner();ensureTrace();$('detailTitle').textContent=task.question;$('detailId').textContent=id;$('detailPill').textContent=task.state;$('detailPill').className=`state-pill ${stateClass(task.state)}`;$('detailState').textContent=(task.execution_status||task.state).toUpperCase();const latest=artifacts[artifacts.length-1];const iteration=status.iteration||{};const current=stageActivity[task.state]||`正在执行 ${task.state}`;const terminal=['REPORT_READY','FAILED','CANCELLED'].includes(task.state);$('activityText').textContent=current;$('activityBanner').classList.toggle('terminal',terminal);$('activityBanner').classList.toggle('failed',task.state==='FAILED');$('detailMeta').innerHTML=`<div class="meta-card"><small>EXECUTION</small><strong class="live">${escapeHtml(task.execution_status||'not_queued')}</strong></div><div class="meta-card"><small>CURRENT ITERATION</small><strong>${iteration.current||task.iteration||0} / ${iteration.maximum||task.max_iterations||0}</strong></div><div class="meta-card"><small>LAST ARTIFACT</small><strong>${escapeHtml(latest?.kind||'waiting')}</strong></div><div class="meta-card"><small>JOB</small><strong>${escapeHtml(jobData.job?.status||task.job_id?.slice(0,8)||'local')}</strong></div>`;ensureActivityBanner();ensureTrace();$('activityText').textContent=current;$('activityBanner').classList.toggle('terminal',terminal);$('activityBanner').classList.toggle('failed',task.state==='FAILED');renderTrace(task.history||[],task.state);const report=artifacts.find(a=>a.kind==='ResearchReport');$('reportBtn').classList.toggle('hidden',!report);$('reportBtn').onclick=()=>showReport(report);renderPipeline(task.state);renderArtifacts(artifacts);if(terminal){clearInterval(timer);timer=null}}catch(e){console.warn(e)}}
function renderTrace(history,state){const list=$('traceList');if(!list)return;$('traceSummary').textContent=`${history.length} 次转换 · 当前 ${state}`;list.innerHTML=history.length?history.map((item,i)=>`<div class="trace-item"><span class="trace-node">${i+1}</span><div><strong>${item.from} <b>→</b> ${item.to}</strong><small>${stageActivity[item.to]||item.to}${item.error?` · ${escapeHtml(item.error)}`:''}</small></div><time>${new Date(item.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time></div>`).join(''):'<div class="trace-empty">任务尚未产生状态转换</div>'}
function renderPipeline(state){const index=stages.findIndex(s=>s[0]===state);$('pipeline').innerHTML=stages.map((s,i)=>`<div class="stage ${i<index?'done':''} ${i===index?'current':''}"><b>${i<index?'✓':s[1]}</b><span>${s[0].replace('_',' ')}</span></div>`).join('')}
function renderArtifacts(arts){$('artifactCount').textContent=`${arts.length} ITEMS`;$('artifacts').innerHTML=arts.length?arts.map((a,i)=>`<div class="artifact" data-artifact="${i}"><div class="artifact-main"><span class="artifact-icon">${icon(a.kind)}</span><div><div class="artifact-kind">${a.kind}</div><div class="artifact-meta">${(a.producer||'control-plane')} · ${(a.artifact_id||'').slice(0,12)}</div></div></div><span class="artifact-status">${a.status||'created'}</span></div>`).join(''):'<div class="empty-state">Waiting for artifacts…</div>'; $('artifacts').querySelectorAll('.artifact').forEach((el,i)=>el.onclick=()=>showArtifact(arts[i]))}
function icon(kind){return ({EvidenceSet:'⌁',LiteratureIntelligence:'◌',ResearchPlan:'◇',HypothesisSet:'?',CodeRevision:'<>',ExperimentRun:'◎',Finding:'∴',ReviewReport:'!',ResearchReport:'▤',ResearchDecision:'↻',ReproducibilityPackage:'✓'}[kind]||'·')}
function showArtifact(a){const payload=a.payload||{};let text='';try{text=JSON.stringify(payload,null,2)}catch(_){text='[无法序列化 Artifact 内容]'}const limit=24000;const clipped=text.length>limit;text=clipped?text.slice(0,limit)+'\n… [内容过长，已截断；请通过 API Artifact 端点查看完整原始记录]':text;const error=a.status==='failed'?(payload.error||payload.stderr||payload.metrics_status||'执行失败，未提供详细原因'):null;$('insight').innerHTML=`<div class="eyebrow">${escapeHtml(a.kind)}</div><h3>${escapeHtml(a.status||'created')}</h3>${error?`<div class="failure-detail"><strong>FAILURE REASON</strong><pre>${escapeHtml(String(error))}</pre></div>`:''}<div class="artifact-summary"><span>PRODUCER</span><b>${escapeHtml(a.producer||'—')}</b><span>SIZE</span><b>${text.length.toLocaleString()} chars${clipped?' (clipped)':''}</b></div><pre class="json-view">${escapeHtml(text)}</pre>`}
function showReport(a){if(!a)return;const p=a.payload||{};const exp=p.experiment||{};const finding=p.finding||{};const review=p.review||{};const demo=p.execution_mode==='synthetic_demo';const trajectory=(exp.trajectory||[]).map((r,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(String(r.iteration??'—'))}</td><td>${escapeHtml(String(r.replicate??'—'))}</td><td>${escapeHtml(JSON.stringify(r.metrics||{}))}</td><td>${escapeHtml(r.status||'—')}</td></tr>`).join('');const hypotheses=(p.hypotheses||[]).map(h=>`<li><b>${escapeHtml(h.id||'H')}</b> ${escapeHtml(h.statement||'')}</li>`).join('');$('insight').innerHTML=`<div class="report-reader"><div class="eyebrow">RESEARCH REPORT · DRAFT FOR HUMAN REVIEW</div>${demo?'<div class="demo-warning">DEMO DATA · THIS REPORT USED FAKE EXPERIMENT OUTPUT</div>':''}<h2>${escapeHtml(p.title||'Research report')}</h2><p class="report-summary">${escapeHtml(p.executive_summary||'')}</p><div class="report-stats"><div><small>EXECUTION MODE</small><b>${demo?'SYNTHETIC DEMO':'REAL CONFIGURED'}</b></div><div><small>OBJECTIVE</small><b>${escapeHtml(p.objective?.metric||'—')}</b></div><div><small>RUNS</small><b>${escapeHtml(String(exp.run_count??'—'))}</b></div></div><h3>Question-specific hypothesis</h3><ul class="hypothesis-list">${hypotheses||'<li>No hypothesis recorded.</li>'}</ul><h3>Finding</h3><p>${escapeHtml(finding.text||'No finding recorded.')}</p><h3>Run trajectory</h3><table class="run-table"><thead><tr><th>#</th><th>ITER</th><th>REP</th><th>METRICS</th><th>STATUS</th></tr></thead><tbody>${trajectory||'<tr><td colspan="5">No run trajectory</td></tr>'}</tbody></table><h3>Review</h3><p>${escapeHtml(review.decision||'Requires human review')}</p><p class="report-note">${demo?'This report is synthetic demo output. Configure a real Coding Agent and experiment command before interpreting results.':'This report is evidence-bound and remains a draft for human scientific review.'}</p></div>`}
$('launchBtn').onclick=launch;$('refreshBtn').onclick=loadMissions;$('backBtn').onclick=()=>{if(timer)clearInterval(timer);timer=null;selected=null;$('detailView').classList.add('hidden');$('overviewView').classList.remove('hidden');$('viewName').textContent='OVERVIEW';loadMissions()};document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');literatureMode=c.dataset.mode});document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>{if(n.dataset.view==='overview')$('backBtn').click();else toast(`${n.textContent.trim()} · 选择一个任务后查看`) });$('apiSettings').onclick=()=>{const next=prompt('AutoResearch API 地址',API);if(next){localStorage.setItem('autoresearch_api',next.replace(/\/$/,''));location.reload()}};loadMissions();
ensureRuntimeFields();ensureObjectiveMetric();document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>{if(n.dataset.view==='overview')$('backBtn').click();else toast(`${n.textContent.trim()} · 选择一个任务后查看`) });$('themeToggle').onclick=()=>{const next=document.body.classList.contains('light')?'dark':'light';localStorage.setItem(THEME_KEY,next);applyTheme(next)};$('apiSettings').onclick=()=>{const next=prompt('AutoResearch API 地址',API);if(next){localStorage.setItem('autoresearch_api',next.replace(/\/$/,''));location.reload()}};loadRuntimeConfig();loadMissions();
// Dependency gates can temporarily retain IMPLEMENTING as the task state.
const _syncDependencyAwareButton=syncPauseButton;syncPauseButton=function(task){if(task?.runtime?.phase==='awaiting_dependency_approval'&&task.runtime?.dependency_approval!==true&&task.state!=='AWAITING_DEPENDENCY_APPROVAL')task={...task,state:'AWAITING_DEPENDENCY_APPROVAL'};return _syncDependencyAwareButton(task)};
const _showArtifact=showArtifact;showArtifact=function(a){if(a?.status==='failed'){const p={...(a.payload||{})};const raw=String(p.error||p.stderr||p.metrics_status||'执行失败，未提供详细原因');const lines=raw.split(/\r?\n/).filter(line=>!/^\s*\d+(?:\.\d+)?%\|/.test(line));p.error=(lines.join('\n').trim()||raw).slice(-4000);a={...a,payload:p}}return _showArtifact(a)};
// Cached reports created before provenance fixes may still say REAL CONFIGURED.
// Reclassify only when explicit provenance is present; trajectory rows contain
// metrics and status only, so missing command fields do not imply Fake.
const _renderReport=showReport;showReport=function(a){if(a&&a.payload&&a.payload.execution_mode==='synthetic_demo'){const metrics=a.payload.experiment?.metrics||{};if(Object.keys(metrics).some(k=>k!=='score'))a={...a,payload:{...a.payload,execution_mode:'real_configured'}}}return _renderReport(a)};
document.addEventListener('click',async e=>{if(e.target.id!=='deleteBtn'||!selected)return;if(!confirm('删除此任务及其 Artifact 记录？本地 Mission 文件默认保留。'))return;const deleteFiles=confirm('是否同时删除该 Mission 的本地文件？\n确定=删除文件，取消=保留文件');try{await api(`/research/${selected}/delete`,{method:'POST',body:JSON.stringify({delete_files:deleteFiles})});toast(deleteFiles?'任务和本地文件已删除':'任务已删除，本地文件已保留');$('backBtn').click()}catch(err){toast(`删除失败 · ${err.message}`)}});
document.addEventListener('click',async e=>{if(e.target.id!=='pauseBtn'||!selected)return;try{const t=(await api(`/research/${selected}`)).task;if(t.state==='AWAITING_DEPENDENCY_APPROVAL'){const req=t.runtime?.dependency_request||{};const packages=(req.missing||[]).join(', ')||'requirements.txt 中的依赖';const approved=confirm(`实验需要安装依赖：${packages}\n路径：${req.requirements_path||'requirements.txt'}\n\n允许使用实验环境的 Python 安装这些依赖吗？`);await api(`/research/${selected}/resume`,{method:'POST',body:JSON.stringify({approve_dependencies:approved})});toast(approved?'已批准安装依赖，任务正在继续':'已拒绝安装依赖，任务已暂停；再次点击 Resume 可重新询问');await refreshDetail(selected);return}const action=t.execution_status==='orphaned'?'retry':(t.state==='PAUSED'?'resume':'pause');if(action==='pause'){const j=(await api(`/research/${selected}/job`).catch(()=>({}))).job;if(!j||!['queued','running'].includes(j.status)){toast('当前任务没有运行中的作业');return}}await api(`/research/${selected}/${action}`,{method:'POST',body:'{}'});toast(action==='retry'?'执行进程已中断，正在重新排队':action==='pause'?'已请求暂停':'任务已恢复');await refreshDetail(selected)}catch(err){toast(`操作失败 · ${err.message}`)}});
// Keep the action label and enabled state synchronized with every status poll.
const _refreshDetail=refreshDetail;refreshDetail=async function(id){await _refreshDetail(id);let card=$('elapsedCard');if(!card){card=document.createElement('div');card.id='elapsedCard';card.className='meta-card';card.innerHTML='<small>ELAPSED</small><strong>—</strong>';$('detailMeta').appendChild(card)}try{const [taskData,jobData]=await Promise.all([api('/research/'+id),api('/research/'+id+'/job').catch(()=>({}))]);syncPauseButton(taskData.task);const started=jobData.job?.started_at?new Date(jobData.job.started_at):null;const elapsed=started?Math.max(0,Math.floor((Date.now()-started.getTime())/1000)):0;const mins=Math.floor(elapsed/60),secs=String(elapsed%60).padStart(2,'0');card.querySelector('strong').textContent=started?String(mins)+':'+secs:'—'}catch(_){}};
// Remove stale rows immediately; the API delete endpoint is idempotent too.
document.addEventListener('click',e=>{if(e.target.id==='deleteBtn'&&selected){const id=selected;missions=missions.filter(m=>m.task_id!==id);renderMissions();}},true);
